version: '3.8'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_USERNAME: "sa"
      SA_PASSWORD: "1Secure*Password1"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"